version: "3.9"
services:
  mysql:
    image: mysql:5.7.40
    container_name: funnymovies-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: funnymovies
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5009:5009"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_REPLICATION_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=funnymovies
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456
      - DATABASE_DIALECT=mysql
      - DATABASE_POOL_MAX=5
      - DATABASE_POOL_MIN=1
      - DATABASE_POOL_ACQUIRE=30000
      - DATABASE_POOL_IDLE=10000
      - SERVER_HOST=localhost
      - SERVER_PORT=5009
      - TOKEN_PRIVATE_KEY=@dshgdsah5466663$@$@:3
      - TOKEN_EXPIRES_IN=86400
      - GOOGLE_API_KEY=AIzaSyD_4YOrE4fSd1JcXTBds1sAzXahTzIOXjg


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - mysql
    environment:
      - REACT_APP_HOST_API=http://localhost:5009/api/
      - REACT_APP_HOST_WSS=http://localhost:5009
      - PORT=3005

volumes:
  mysql-data:
